ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.ksuzuki.WebsocketsKt.configureWebsockets
      - com.ksuzuki.RoutingKt.configureRouting
      - com.ksuzuki.SerializationKt.configureSerialization
      - com.ksuzuki.ThymeleafKt.configureThymeleaf
